"""One-off style generator for UniST / OpenCity / FactoST sharded cross-domain YAMLs. Not part of install."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

HDR = """# Auto-generated by scripts/data/_gen_sharded_non_dpm_yamls.py — sharded 5 sources + 5 targets.
# Build shards: python scripts/data/build_largest_cross_domain_shards.py --num-shards 2 --target-nodes 256
# Split [0.7,0.1,0.2]; pretrain 10000 steps/epoch; pretrain val/test cap 256/512; target val/test 512/1024.
"""

REGISTRY = r"""dataset_registry:
  LargeST_xd_part0:
    name: LargeST_xd_part0
    data_path: data/LargeST_xd_part0/data.npz
    graph_path: data/LargeST_xd_part0/adj.npz
    batch_size: 4
  LargeST_xd_part1:
    name: LargeST_xd_part1
    data_path: data/LargeST_xd_part1/data.npz
    graph_path: data/LargeST_xd_part1/adj.npz
    batch_size: 4
  KnowAir:
    name: KnowAir
    data_path: data/KnowAir/data.npz
    graph_path: data/KnowAir/adj.npz
    batch_size: 4
  Weather:
    name: Weather
    data_path: data/Weather/data.npz
    graph_path: data/Weather/adj.npz
    batch_size: 4
  ETTm1:
    name: ETTm1
    data_path: data/ETTm1/data.npz
    graph_path: data/ETTm1/adj.npz
    batch_size: 4
  METR-LA:
    name: METR-LA
    data_path: data/METR-LA/data.npz
    graph_path: data/METR-LA/adj.npz
    batch_size: 8
  PEMS04:
    name: PEMS04
    data_path: data/PEMS04/data.npz
    graph_path: data/PEMS04/adj.npz
    batch_size: 8
  PEMS07:
    name: PEMS07
    data_path: data/PEMS07/data.npz
    graph_path: data/PEMS07/adj.npz
    batch_size: 8
  PEMS08:
    name: PEMS08
    data_path: data/PEMS08/data.npz
    graph_path: data/PEMS08/adj.npz
    batch_size: 8
  ETTm2:
    name: ETTm2
    data_path: data/ETTm2/data.npz
    graph_path: data/ETTm2/adj.npz
    batch_size: 8

dataset_groups:
  cross_domain_sharded_sources:
    - LargeST_xd_part0
    - LargeST_xd_part1
    - KnowAir
    - Weather
    - ETTm1

data:
  type: WindowDataModule
  dataset_key: METR-LA
  input_len: 96
  output_len: 96
  batch_size: 8
  split: [0.7, 0.1, 0.2]
  scaler:
    type: standard

"""

TAIL_DATA = r"""        max_val_windows: 512
        max_test_windows: 1024
        scaler:
          type: standard
"""

TARGETS: list[tuple[str, str, str]] = [
    ("metr_la", "METR-LA", "METR-LA"),
    ("pems04", "PEMS04", "PEMS04"),
    ("pems07", "PEMS07", "PEMS07"),
    ("pems08", "PEMS08", "PEMS08"),
    ("ettm2", "ETTm2", "ETTm2"),
]


def unist_yaml() -> str:
    m = r"""model:
  type: UniSTFoundationModel
  num_nodes: auto
  input_dim: auto
  output_dim: auto
  input_len: auto
  output_len: auto
  hidden_dim: 128
  encoder_layers: 6
  decoder_layers: 4
  num_heads: 8
  ffn_dim: 256
  use_prompt: true
  num_memory_spatial: 128
  num_memory_temporal: 128

"""
    out = [HDR, "experiment_name: unist_cross_domain_sharded_transfer\nseed: 42\n\ntrainer:\n  type: MultiStageTrainer\n  device: auto\n  work_dir: runs/unist_cross_domain_sharded_transfer\n  log_every: 50\n\n", REGISTRY, m]
    out.append(
        """pipeline:
  stages:
    - name: unist_cross_domain_sharded_pretrain
      save_artifact: unist_xd_sharded_pretrain
      reset_data: true
      data:
        type: MultiDatasetWindowDataModule
        dataset_group: cross_domain_sharded_sources
        input_len: 96
        output_len: 96
        num_workers: 2
        train_strategy: round_robin
        eval_strategy: per_dataset
        steps_per_epoch: 10000
        max_val_windows: 256
        max_test_windows: 512
        split: [0.7, 0.1, 0.2]
        scaler:
          type: standard
      epochs: 10
      model:
        use_prompt: false
      task:
        type: MaskedReconstructionTask
        mask_ratio: 0.5
        mask_strategy: mixed
        mask_strategies: [random, temporal, tube, block]
      losses:
        - type: mse
      metrics:
        - type: mae
      optimizer:
        type: AdamW
        lr: 0.001
        weight_decay: 0.0001
      scheduler:
        type: CosineAnnealingLR
        T_max: 10
      validate_every: 1
      gradient_clip_val: 5.0
"""
    )
    for key, dkey, _ in TARGETS:
        out.append(
            f"""
    - name: {key}_zero_shot
      eval_only: true
      epochs: 0
      reset_data: true
      data:
        type: WindowDataModule
        dataset_key: {dkey}
        input_len: 96
        output_len: 96
        batch_size: 8
        split: [0.7, 0.1, 0.2]
{TAIL_DATA}
      load_from: unist_xd_sharded_pretrain
      load_method: load_backbone_weights
      strict_load: false
      model:
        use_prompt: true
      task:
        type: MaskedForecastCompletionTask
      losses:
        - type: mae
      metrics:
        - type: mae
        - type: rmse

    - name: {key}_five_percent_prompt_tuning
      epochs: 3
      reset_data: true
      data:
        type: WindowDataModule
        dataset_key: {dkey}
        input_len: 96
        output_len: 96
        batch_size: 8
        split: [0.7, 0.1, 0.2]
{TAIL_DATA}
      load_from: unist_xd_sharded_pretrain
      load_method: load_backbone_weights
      strict_load: false
      model:
        use_prompt: true
      few_shot_ratio: 0.05
      freeze:
        - all
      unfreeze:
        - prompt.*
        - reconstruction_head.*
      task:
        type: MaskedForecastCompletionTask
      losses:
        - type: mae
          weight: 1.0
        - type: mse
          weight: 0.05
      metrics:
        - type: mae
        - type: rmse
      optimizer:
        type: AdamW
        lr: 0.0005
        weight_decay: 0.0001
      scheduler:
        type: CosineAnnealingLR
        T_max: 3
      validate_every: 1
      gradient_clip_val: 5.0
"""
        )
    return "".join(out)


def opencity_yaml() -> str:
    m = r"""model:
  type: OpenCityFoundationModel
  num_nodes: auto
  input_dim: auto
  output_dim: auto
  input_len: auto
  output_len: auto
  hidden_dim: 128
  num_layers: 4
  num_heads: 4
  ffn_dim: 256
  dropout: 0.1

"""
    out = [HDR, "experiment_name: opencity_cross_domain_sharded_transfer\nseed: 42\n\ntrainer:\n  type: MultiStageTrainer\n  device: auto\n  work_dir: runs/opencity_cross_domain_sharded_transfer\n  log_every: 50\n\n", REGISTRY, m]
    out.append(
        """pipeline:
  stages:
    - name: opencity_cross_domain_sharded_pretrain
      save_artifact: opencity_xd_sharded_pretrain
      reset_data: true
      data:
        type: MultiDatasetWindowDataModule
        dataset_group: cross_domain_sharded_sources
        input_len: 96
        output_len: 96
        num_workers: 2
        train_strategy: round_robin
        eval_strategy: per_dataset
        steps_per_epoch: 10000
        max_val_windows: 256
        max_test_windows: 512
        split: [0.7, 0.1, 0.2]
        scaler:
          type: standard
      epochs: 10
      task:
        type: ForecastingTask
      losses:
        - type: mae
          weight: 1.0
        - type: mse
          weight: 0.05
      metrics:
        - type: mae
        - type: rmse
      optimizer:
        type: AdamW
        lr: 0.001
        weight_decay: 0.0001
      scheduler:
        type: CosineAnnealingLR
        T_max: 10
      validate_every: 1
      gradient_clip_val: 5.0
"""
    )
    for key, dkey, _ in TARGETS:
        out.append(
            f"""
    - name: {key}_zero_shot
      eval_only: true
      epochs: 0
      reset_data: true
      data:
        type: WindowDataModule
        dataset_key: {dkey}
        input_len: 96
        output_len: 96
        batch_size: 8
        split: [0.7, 0.1, 0.2]
{TAIL_DATA}
      load_from: opencity_xd_sharded_pretrain
      strict_load: true
      task:
        type: ForecastingTask
        model_mode: zero_shot
      losses:
        - type: mae
      metrics:
        - type: mae
        - type: rmse

    - name: {key}_five_percent_head_tuning
      epochs: 3
      reset_data: true
      data:
        type: WindowDataModule
        dataset_key: {dkey}
        input_len: 96
        output_len: 96
        batch_size: 8
        split: [0.7, 0.1, 0.2]
{TAIL_DATA}
      load_from: opencity_xd_sharded_pretrain
      strict_load: true
      few_shot_ratio: 0.05
      freeze:
        - all
      unfreeze:
        - forecast_head.*
      task:
        type: ForecastingTask
      losses:
        - type: mae
          weight: 1.0
        - type: mse
          weight: 0.05
      metrics:
        - type: mae
        - type: rmse
      optimizer:
        type: AdamW
        lr: 0.0005
        weight_decay: 0.0001
      scheduler:
        type: CosineAnnealingLR
        T_max: 3
      validate_every: 1
      gradient_clip_val: 5.0
"""
        )
    return "".join(out)


def factost_yaml() -> str:
    m = r"""model:
  type: FactoSTFoundationModel
  num_nodes: auto
  input_dim: auto
  output_dim: auto
  input_len: auto
  output_len: auto
  patch_len: 12
  hidden_dim: 128
  num_layers: 3
  num_heads: 8
  ffn_dim: 256
  num_prompt_tokens: 3
  use_st_adapter: true

"""
    out = [HDR, "experiment_name: factost_cross_domain_sharded_transfer\nseed: 42\n\ntrainer:\n  type: MultiStageTrainer\n  device: auto\n  work_dir: runs/factost_cross_domain_sharded_transfer\n  log_every: 50\n\n", REGISTRY, m]
    out.append(
        """pipeline:
  stages:
    - name: factost_sharded_universal_temporal_pretrain
      save_artifact: factost_xd_sharded_utp
      reset_data: true
      data:
        type: MultiDatasetWindowDataModule
        dataset_group: cross_domain_sharded_sources
        input_len: 96
        output_len: 96
        num_workers: 2
        train_strategy: round_robin
        eval_strategy: per_dataset
        steps_per_epoch: 10000
        max_val_windows: 256
        max_test_windows: 512
        split: [0.7, 0.1, 0.2]
        scaler:
          type: standard
      epochs: 10
      model:
        use_st_adapter: false
      task:
        type: JointReconstructionForecastTask
        mask_ratio: 0.5
        mask_strategy: random
        reconstruction_weight: 1.0
        forecast_weight: 1.0
        reconstruction_spectral_weight: 0.1
        forecast_spectral_weight: 0.1
        spectral_scales: [1, 2, 4]
      losses:
        - type: mse
      metrics:
        - type: mae
      optimizer:
        type: AdamW
        lr: 0.001
        weight_decay: 0.0001
      scheduler:
        type: CosineAnnealingLR
        T_max: 10
      validate_every: 1
      gradient_clip_val: 5.0
"""
    )
    for key, dkey, _ in TARGETS:
        out.append(
            f"""
    - name: {key}_zero_shot
      eval_only: true
      epochs: 0
      reset_data: true
      data:
        type: WindowDataModule
        dataset_key: {dkey}
        input_len: 96
        output_len: 96
        batch_size: 8
        split: [0.7, 0.1, 0.2]
{TAIL_DATA}
      load_from: factost_xd_sharded_utp
      strict_load: true
      model:
        use_st_adapter: false
        output_dim: 1
      task:
        type: ForecastingTask
        model_mode: zero_shot
      losses:
        - type: mae
      metrics:
        - type: mae
        - type: rmse

    - name: {key}_five_percent_factorized_adapter
      epochs: 3
      reset_data: true
      data:
        type: WindowDataModule
        dataset_key: {dkey}
        input_len: 96
        output_len: 96
        batch_size: 8
        split: [0.7, 0.1, 0.2]
{TAIL_DATA}
      load_from: factost_xd_sharded_utp
      load_method: load_backbone_weights
      strict_load: false
      model:
        use_st_adapter: true
      few_shot_ratio: 0.05
      freeze:
        - all
      unfreeze:
        - prompt_*
        - st_*
        - metadata_gate.*
        - forecast_head.*
      task:
        type: ForecastingTask
      losses:
        - type: mae
          weight: 1.0
        - type: mse
          weight: 0.05
      metrics:
        - type: mae
        - type: rmse
      optimizer:
        type: AdamW
        lr: 0.0005
        weight_decay: 0.0001
      scheduler:
        type: CosineAnnealingLR
        T_max: 3
      validate_every: 1
      gradient_clip_val: 5.0
"""
        )
    return "".join(out)


def main() -> None:
    out = ROOT / "configs" / "cross_domain"
    (out / "unist_cross_domain_sharded_transfer.yaml").write_text(unist_yaml(), encoding="utf-8")
    (out / "opencity_cross_domain_sharded_transfer.yaml").write_text(opencity_yaml(), encoding="utf-8")
    (out / "factost_cross_domain_sharded_transfer.yaml").write_text(factost_yaml(), encoding="utf-8")
    print("Wrote 3 files under", out)


if __name__ == "__main__":
    main()
